### ISSUE TITLE
Error in documentation for mso_schema_template_external_epg_subnet - import statement incorrect

### ISSUE THREAD

**Issue by mike-guy** [CiscoDevNet/terraform-provider-mso#107]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Documentation error
The documentation for the mso_schema_template_external_epg_subnet (https://registry.terraform.io/providers/CiscoDevNet/mso/latest/docs/resources/schema_template_external_epg_subnet) states that the import command should look like

```
terraform import mso_schema_template_external_epg_subnet.subnet1 {schema_id}/template/{template_name}/externalEPG/{external_epg_name}/subnet/{ip}

```

This is incorrect, it should be...

```
terraform import mso_schema_template_external_epg_subnet.subnet1 {schema_id}/template/{template_name}/externalEPG/{external_epg_name}/ip/{ip}

```
#106

**Comment by shrsr** [comment]
Closing this issue because it was fixed in #106
