### ISSUE TITLE
Option to add subnet name under mso_schema_site_vrf_region / cidr / subnet

### ISSUE THREAD

**Issue by marinalf** [CiscoDevNet/terraform-provider-mso#122]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Need an option to define subnet name under resource mso_schema_site_vrf_region / cidr / subnet, same way we have for the ACI provider under resource aci_cloud_subnet. 

### New or Affected Resource(s) + MSO Class(es):

mso_schema_site_vrf_region

### MSO version

*3.6

### APIC version and APIC Platform for Site level Resources

*Version 25.0(x)
*Cloud ACI in AWS/Azure/GCP

### Potential Terraform Configuration

```hcl
resource "mso_schema_site_vrf_region" "aws_region" {
  schema_id          = mso_schema.schema1.id
  template_name      = mso_schema_site.aws_site.template_name
  site_id            = data.mso_site.aws_site.id
  vrf_name           = mso_schema_site_vrf.aws_site.vrf_name
  region_name        = var.region_name
  vpn_gateway        = false
  hub_network_enable = true
  hub_network = {
    name        = var.tgw_name
    tenant_name = "infra"
  }
  cidr {
    cidr_ip = var.cidr_ip
    primary = true

    subnet {
      ip    = var.cloud_subnet_tgw-a
      name = var.subnet_name_tgw-a
      zone  = var.zone1
      usage = "gateway"
    }

    subnet {
      ip    = var.cloud_subnet_tgw-b
      name = var.subnet_name_tgw-b
      zone  = var.zone2
      usage = "gateway"
    }

    subnet {
      ip   = var.cloud_subnet_user1
      name = var.subnet_name_user1
      zone = var.zone3
      usage = "user"
    }
```

**Comment by shrsr** [comment]
@marinalf My apologies. We don't have the subnet name attribute in resource_mso_schema_site_vrf_region_cidr_subnet. We'll take care of this.
