### ISSUE TITLE
Unable to create cloud EPG with resource mso_schema_template_anp_epg

### ISSUE THREAD

**Issue by marinalf** [CiscoDevNet/terraform-provider-mso#123]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.0.11

### MSO version

*3.6
provider: v0.5.0

### APIC version and APIC Platform for Site Level Resources

*Version 25.0(x)
*Cloud ACI in AWS/Azure/GCP

### Affected Resource(s)

mso_schema_template_anp_epg

### Terraform Configuration Files

```hcl
resource "mso_schema_template_anp" "ap" {
  schema_id    = mso_schema.schema1.id
  template     = mso_schema.schema1.template_name
  name         = var.ap_name
  display_name = var.ap_name
}

resource "mso_schema_site_anp" "aws" {
  schema_id     = mso_schema.schema1.id
  anp_name      = mso_schema_template_anp.ap.name
  template_name = mso_schema_site.aws_site.template_name
  site_id       = data.mso_site.aws_site.id
}

resource "mso_schema_site_anp_epg" "aws_epg" {
  schema_id     = mso_schema.schema1.id
  template_name = mso_schema_site.aws_site.template_name
  site_id       = data.mso_site.aws_site.id
  anp_name      = mso_schema_site_anp.aws.anp_name
  epg_name      = mso_schema_template_anp_epg.cloud_epg.name
}

resource "mso_schema_template_anp_epg" "cloud_epg" {
  schema_id                  = mso_schema.schema1.id
  template_name              = mso_schema.schema1.template_name
  anp_name                   = mso_schema_template_anp.ap.name
  name                       = var.epg_name
  vrf_name                   = mso_schema_template_vrf.vrf1.name
}
```

### Actual Behavior

Plan: 14 to add, 0 to change, 0 to destroy.
mso_tenant.tenant: Creating...
mso_tenant.tenant: Creation complete after 2s [id=622bde461e00001612133f33]
mso_schema.schema1: Creating...
mso_schema.schema1: Creation complete after 0s [id=622bde461e00001312133f34]
mso_schema_site.azure_site: Creating...
mso_schema_site.azure_site: Creation complete after 0s [id=622b606a26faa061c096c60a]
mso_schema_template_anp.ap: Creating...
mso_schema_template_anp.ap: Creation complete after 0s [id=MyApp]
mso_schema_site.aws_site: Creating...
mso_schema_site.aws_site: Creation complete after 0s [id=622ad0706ce5d801e0b10f83]
mso_schema_template_vrf.vrf1: Creating...
mso_schema_template_vrf.vrf1: Creation complete after 1s [id=vrf1]
mso_schema_site_anp.aws: Creating...
mso_schema_site_anp.aws: Creation complete after 0s [id=MyApp]
mso_schema_site_vrf.aws_site: Creating...
mso_schema_site_vrf.aws_site: Creation complete after 0s [id=vrf1]
mso_schema_template_anp_epg.cloud_epg: Creating...
mso_schema_site_vrf.azure_site: Creating...
mso_schema_site_vrf.azure_site: Creation complete after 0s [id=vrf1]
mso_schema_site_vrf_region.aws_region: Creating...
mso_schema_site_vrf_region.aws_region: Creation complete after 1s [id=us-east-1]
╷
│ Error: "Bad Request: incomplete ref: /622bde461e00001312133f34/policy-stretch. If non-empty, must provide policy name"{}
│ 
│   with mso_schema_template_anp_epg.cloud_epg,
│   on main.tf line 152, in resource "mso_schema_template_anp_epg" "cloud_epg":
│  152: resource "mso_schema_template_anp_epg" "cloud_epg" {
│ 

### Steps to Reproduce

1. `terraform apply`

https://github.com/marinalf/ndo-demo-terraform/blob/main/main.tf

### Important Factoids

I have looked at other issues with similar error output, switched the order with resource mso_schema_site_anp_epg, added implicit dependencies, but same outcome. The sample config provided on issue #83 also did not work. There is no problem up to the application profile, it starts when adding the cloud EPG resource. 

### References

* #96

**Comment by marinalf** [comment]
I managed to get it running after adding bd_name under the resource. This should not be a requirement for cloud EPG.

Final config:

```hcl
resource "mso_schema_template_anp_epg" "cloud_epg" {
  schema_id                  = mso_schema.schema1.id
  template_name              = mso_schema.schema1.template_name
  anp_name                   = mso_schema_template_anp.ap.name
  name                       = var.epg_name
  bd_name                    = var.bd_name # this should not be required for Cloud sites
  vrf_name                   = mso_schema_template_vrf.vrf1.name
}
```

**Comment by lhercot** [comment]
I think this is the same (but opposite) issue as #111 they should be addressed together.
