### ISSUE TITLE
Incomplete state data on imported mso_schema_template_anp_epg

### ISSUE THREAD

**Issue by justlikeef** [CiscoDevNet/terraform-provider-mso#133]
mso_schema_template_anp_epg was successfully imported from ndo into the state file, but the data is incomplete.  Sites are on prem, so according to the documentation:

[bd_name](https://registry.terraform.io/providers/CiscoDevNet/mso/latest/docs/resources/schema_template_anp_epg#bd_name) - (Optional) Name of Bridge Domain. It is required when using on-premise sites.

Example of what is imported into the state file:

> {
>       "mode": "managed",
>       "type": "mso_schema_template_anp_epg",
>       "name": "mso_schema_template_anp_epg-mso-ndo-test-EPG-db8a818bbeafc9fb77420c1d3757bbed",
>       "provider": "provider[\"registry.terraform.io/ciscodevnet/mso\"].ndo",
>       "instances": [
>         {
>           "schema_version": 1,
>           "attributes": {
>             "access_type": null,
>             "anp_name": "NC-AP",
>             "bd_name": null,
>             "bd_schema_id": null,
>             "bd_template_name": null,
>             "custom_service_type": null,
>             "deployment_type": null,
>             "display_name": "Testing-EPG",
>             "epg_type": "application",
>             "id": "Testing-EPG",
>             "intersite_multicast_source": false,
>             "intra_epg": "unenforced",
>             "name": "Testing-EPG",
>             "preferred_group": false,
>             "proxy_arp": false,
>             "schema_id": "60edca36360000e862101505",
>             "service_type": null,
>             "template_name": "Template1",
>             "useg_epg": false,
>             "vrf_name": null,
>             "vrf_schema_id": null,
>             "vrf_template_name": null
>           },
>           "sensitive_attributes": [],
>           "private": "########"
>         }
>       ]
>     },
> 

There are other attributes that are also required for on-prem deployments, and when they are all populated, populating the bd_name says that it forces a replacement...

>   # mso_schema_template_anp_epg.mso_schema_template_anp_epg-mso-ndo-Testing-EPG-db8a818bbeafc9fb77420c1d3757bbed must be replaced
> -/+ resource "mso_schema_template_anp_epg" "mso_schema_template_anp_epg-mso-ndo-Testing-EPG-db8a818bbeafc9fb77420c1d3757bbed" {
>       + bd_name                    = "Testing-BD" # forces replacement
>       + bd_schema_id               = "60edca36360000e862101505"
>       + bd_template_name           = "Template1"
>       ~ id                         = "Testing-EPG" -> (known after apply)
>         name                       = "Testing-EPG"
>       + vrf_schema_id              = (known after apply)
>       + vrf_template_name          = (known after apply)
>         # (10 unchanged attributes hidden)
>     }
> 

### Terraform Version

Terraform v1.1.7
on linux_amd64
+ provider registry.terraform.io/ciscodevnet/aci v2.1.0
+ provider registry.terraform.io/ciscodevnet/mso v0.6.0

### MSO version

* V 3.6(1e)

**Comment by shrsr** [comment]
@justlikeef Was the BD configured on NDO before importing the resource?

**Comment by lhercot** [comment]
@justlikeef Any update on this?

**Comment by justlikeef** [comment]
It was created in an older version of NDO which had to be rebuilt from
scratch and the backup could not be used because there was a bug where the
default cluster name was written to the backup instead of the real name.
When we rebuilt the cluster, we had to import the config from the APIC at
each site.

**Comment by shrsr** [comment]
#129 Fixes this issue. It will be incorporated on the next release.
