### ISSUE TITLE
Error: The terraform-provider-mso_v0.6.0 plugin crashed! when run mso_site with NDO Version: 3.6(1e)

### ISSUE THREAD

**Issue by lwlxwang** [CiscoDevNet/terraform-provider-mso#134]
### Terraform Version
Terraform v1.1.7
on darwin_amd64
+ provider registry.terraform.io/ciscodevnet/aci v2.1.0
+ provider registry.terraform.io/ciscodevnet/mso v0.6.0

### MSO version
NDO
Orchestrator
Version: 3.6(1e)

### APIC version and APIC Platform for Site Level Resources

APIC
Version 5.2(4d)

### Terraform Configuration Files

terraform {
  required_providers {
    mso = {
      source = "CiscoDevNet/mso"
    }
    aci = {
      source = "CiscoDevNet/aci"
    }
  }
}

provider "mso" {
  username = var.mso_user.username
  password = var.mso_user.password
  url      = var.mso_user.url
  insecure = true
}

provider "aci" {
  username = var.aci_user.username
  password = var.aci_user.password
  url      = var.aci_user.url
  insecure = true
}

data "mso_site" "on_premises" {
  name          = "BGL"
}

### Steps to Reproduce

% terraform plan        
╷
│ Error: Plugin did not respond
│ 
│   with data.mso_site.on_premises,
│   on MSO_OSPF_Combined1.tf line 27, in data "mso_site" "on_premises":
│   27: data "mso_site" "on_premises" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadDataSource call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-mso_v0.6.0 plugin:

panic: interface conversion: interface {} is nil, not []interface {}

goroutine 82 [running]:
github.com/terraform-providers/terraform-provider-mso/mso.datasourceMSOSiteRead(0xc0001a61c0, 0x1cec7a0, 0xc0004ac070, 0xc0001a61c0, 0x0)
        github.com/terraform-providers/terraform-provider-mso/mso/datasource_mso_site.go:184 +0x1dfe
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).ReadDataApply(0xc000694480, 0xc00000c860, 0x1cec7a0, 0xc0004ac070, 0xc0003d43c8, 0x1, 0x0)
        github.com/hashicorp/terraform-plugin-sdk@v1.14.0/helper/schema/resource.go:403 +0x88
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).ReadDataApply(0xc0001aa000, 0xc000017ad0, 0xc00000c860, 0xc00000c860, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk@v1.14.0/helper/schema/provider.go:451 +0x8f
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadDataSource(0xc000192000, 0x1fc4ea0, 0xc00026c5a0, 0xc000652440, 0xc000192000, 0xc00026c5a0, 0xc0006b0b78)
        github.com/hashicorp/terraform-plugin-sdk@v1.14.0/internal/helper/plugin/grpc_provider.go:1036 +0x45d
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadDataSource_Handler(0x1d048c0, 0xc000192000, 0x1fc4ea0, 0xc00026c5a0, 0xc0000a06c0, 0x0, 0x1fc4ea0, 0xc00026c5a0, 0xc0007ae150, 0x67)
        github.com/hashicorp/terraform-plugin-sdk@v1.14.0/internal/tfplugin5/tfplugin5.pb.go:3341 +0x217
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000682900, 0x1fd0720, 0xc000683800, 0xc000390200, 0xc00068d3e0, 0x2743670, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.27.1/server.go:1024 +0x501
google.golang.org/grpc.(*Server).handleStream(0xc000682900, 0x1fd0720, 0xc000683800, 0xc000390200, 0x0)
        google.golang.org/grpc@v1.27.1/server.go:1313 +0xd3d
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000032250, 0xc000682900, 0x1fd0720, 0xc000683800, 0xc000390200)
        google.golang.org/grpc@v1.27.1/server.go:722 +0xa1
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.27.1/server.go:720 +0xa1

Error: The terraform-provider-mso_v0.6.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by shrsr** [comment]
@lwlxwang If we want to use terraform-provider-mso on NDO, we need to set `platform = "nd"` in the mso provider block as shown below -

```
provider "mso" {
  username = var.mso_user.username
  password = var.mso_user.password
  url = var.mso_user.url
  platform = "nd"
  insecure = true
}
```

Please let us know if you have any questions.

**Comment by lwlxwang** [comment]
Changed my tf code to below, still got crashed.

terraform {
  required_providers {
    mso = {
      source = "CiscoDevNet/mso"
    }
    aci = {
      source = "CiscoDevNet/aci"
    }
    vsphere = {
      source = "hashicorp/vsphere"
    }
  }
}

provider "mso" {
  username  = var.mso_user.username
  password  = var.mso_user.password
  url             = var.mso_user.url
  platform   = "nd"
  insecure   = true
}

provider "aci" {
  username = var.aci_user.username
  password = var.aci_user.password
  url      = var.aci_user.url
  insecure = true
}

data "mso_site" "on_premises" {
  name          = var.onprem_site_name
}


lxwang@LXWANG-M-M5MH test_NDO % terraform plan
╷
│ Error: Plugin did not respond
│ 
│   with data.mso_site.on_premises,
│   on MSO_OSPF_Combined.tf line 38, in data "mso_site" "on_premises":
│   38: data "mso_site" "on_premises" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadDataSource call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-mso_v0.6.0 plugin:

panic: interface conversion: interface {} is nil, not []interface {}

goroutine 51 [running]:
github.com/terraform-providers/terraform-provider-mso/mso.datasourceMSOSiteRead(0xc000272070, 0x1cec7a0, 0xc00051e000, 0xc000272070, 0x0)
        github.com/terraform-providers/terraform-provider-mso/mso/datasource_mso_site.go:101 +0x1ea2
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).ReadDataApply(0xc00057ebd0, 0xc0002044a0, 0x1cec7a0, 0xc00051e000, 0xc00009a930, 0x1, 0x0)
        github.com/hashicorp/terraform-plugin-sdk@v1.14.0/helper/schema/resource.go:403 +0x88
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).ReadDataApply(0xc00011a000, 0xc0001e1ad0, 0xc0002044a0, 0xc0002044a0, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk@v1.14.0/helper/schema/provider.go:451 +0x8f
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadDataSource(0xc00000e008, 0x1fc4ea0, 0xc0003fba40, 0xc000924000, 0xc00000e008, 0xc0003fba40, 0xc0005d0b78)
        github.com/hashicorp/terraform-plugin-sdk@v1.14.0/internal/helper/plugin/grpc_provider.go:1036 +0x45d
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadDataSource_Handler(0x1d048c0, 0xc00000e008, 0x1fc4ea0, 0xc0003fba40, 0xc000200660, 0x0, 0x1fc4ea0, 0xc0003fba40, 0xc00030a100, 0x73)
        github.com/hashicorp/terraform-plugin-sdk@v1.14.0/internal/tfplugin5/tfplugin5.pb.go:3341 +0x217
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000782900, 0x1fd0720, 0xc000783500, 0xc000130200, 0xc000183bf0, 0x2743670, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.27.1/server.go:1024 +0x501
google.golang.org/grpc.(*Server).handleStream(0xc000782900, 0x1fd0720, 0xc000783500, 0xc000130200, 0x0)
        google.golang.org/grpc@v1.27.1/server.go:1313 +0xd3d
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0000344f0, 0xc000782900, 0x1fd0720, 0xc000783500, 0xc000130200)
        google.golang.org/grpc@v1.27.1/server.go:722 +0xa1
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.27.1/server.go:720 +0xa1

Error: The terraform-provider-mso_v0.6.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

lxwang@LXWANG-M-M5MH test_NDO %

**Comment by shrsr** [comment]
Closing the issue because it has been resolved.
