### ISSUE TITLE
Azure shared subscription

### ISSUE THREAD

**Issue by jufonsec** [CiscoDevNet/terraform-provider-mso#2]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Missing capability of selecting "shared" subscription during site association in tenant creation. This allows the same subscription to be used across multiple tenants.

Currently, "azure_access_type" property can be "credentials" (unmanaged) or "managed".

### New or Affected Resource(s) + MSO Class(es):

resource_mso_tenant.go

### MSO version

* V3.0(2d)

### APIC version and APIC Platform for Site level Resources

* cloud-azure V3.0(2d)

**Comment by nkatarmal-crest** [comment]
This is issue has been fixed in the latest version of the provider.
