### ISSUE TITLE
`mso_schema_template_vrf` not working with documented values on v0.10.0

### ISSUE THREAD

**Issue by edudppaz** [CiscoDevNet/terraform-provider-mso#209]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.4.5

### MSO version

* V 2.3(1c) (Nexus dashboard)

### APIC version and APIC Platform for Site Level Resources

* V 5.2(7f) and on-prem

### Affected Resource(s)

* mso_schema_template_vrf

### Terraform Configuration Files

```hcl
resource "mso_schema_template_vrf" "l2_stretched_vrf" {
  for_each         = { for tn in try(local.tenant_policies, []) : tn.name => tn }
  schema_id        = mso_schema.schemas[each.key].id
  template         = "L2-STRETCHED"
  name             = each.value.l2_vrf
  display_name     = each.value.l2_vrf
  layer3_multicast = false
  vzany            = false
  depends_on = [
    mso_schema.schemas
  ]
}
```

### Debug Output

```
[ERROR] vertex "module.tf-aci-ndo.mso_schema_template_vrf.l2_stretched_vrf[\"FT_2\"]" error: "invalid Enablement \"\""{}
│ Error: "invalid Enablement \"\""{}
│
│   with module.tf-aci-ndo.mso_schema_template_vrf.l2_stretched_vrf["FT_2"],
│   on modules/tf-aci-ndo/main.tf line 96, in resource "mso_schema_template_vrf" "l2_stretched_vrf":
│   96: resource "mso_schema_template_vrf" "l2_stretched_vrf" {
│
╵
```

### Expected Behavior

The VRF should be created

### Actual Behavior

VRF is not being created due to bug (or undocumented change)

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Working on 0.9.0, stopped working on 0.10.0. The debug shows, that on v0.9.0, two parameters marked as Optional on the documentation (ipDataPlaneLearning and preferredGroup) were NOT being sent to MSO/APIC, therefore APIC is taking the default values for the parameters

```
[DEBUG] provider.terraform-provider-mso_v0.9.0: [DEBUG] Patch Request Container: [{"op":"add","path":"/templates/L2-STRETCHED/vrfs/-","value":{"displayName":"L2_VRF","l3MCast":false,"name":"L2_VRF","vzAnyEnabled":false}}]
```

On v0.10.0, this parameters are now being sent, and `ipDataPlaneLearning` is empty:

```
[DEBUG] provider.terraform-provider-mso_v0.10.0: [DEBUG] Patch Request Container: [{"op":"add","path":"/templates/L2-STRETCHED/vrfs/-","value":{"displayName":"L2_VRF","ipDataPlaneLearning":"","l3MCast":false,"name":"L2_VRF","preferredGroup":false,"vzAnyEnabled":false}}]
```

This is being rejected by NDO/APIC. Manually setting the `ipDataPlaneLearning` on the terraform file, makes the configuration go through. Therefore, either this parameter is now a **required** parameter, or there is an error on the code as these two parameters _should not_ be sent by default, or sent with their default values.

### References

* #0000

**Comment by akinross** [comment]
Hi @edudppaz,

Thank you for raising the issue, I just validated the same. Will add your PR to the review process.

**Comment by akinross** [comment]
@edudppaz found issue: fix for the empty string was commited on the mso-go-client 1.12.0 and the terraform module is using the previous version 1.11.2
