### ISSUE TITLE
Cannot add site with mso_site

### ISSUE THREAD

**Issue by juchowan** [CiscoDevNet/terraform-provider-mso#224]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.5.1
on darwin_amd64
provider registry.terraform.io/ciscodevnet/mso v0.9.0

### MSO version

* V 3.7.2i

### APIC version and APIC Platform for Site Level Resources

* V 5.2.7f and on-prem

### Affected Resource(s)

* mso_site

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
provider "mso" {
  insecure = true
  platform = "nd"
}

resource "mso_site" "site" {
  name = "site1"
  apic_site_id = "5"
}

```

### Debug Output

[debug](https://gist.github.com/juchowan/581c67f74b3b89111f10293b076114df)

### Expected Behavior

Site should be registered and in NDO we should see site_ID assigned and status changed to Managed. When checking state of this resource we should receive id of this object

### Actual Behavior

Site is not registered, status is still unmanaged. When checking state of this resource we get jsonencode 

```hcl
# mso_site.site:
resource "mso_site" "site" {
    apic_site_id     = "5"
    cloud_providers  = []
    id               = jsonencode({})
    labels           = []
    maintenance_mode = false
    name             = jsonencode({})
    platform         = "on-premise"
    username         = jsonencode({})
}
```

### Steps to Reproduce

1. `terraform apply`
2. `terraform state show mso_site.site`

### References

* #0000

**Comment by anvitha-jain** [comment]
@juchowan
nd_site adds the site to ND and mso_site turns the "managed" flag on. So, my question to you would be, is the site already registered with ND? Because, when mso_site is used for ND it is only to turn the managed flag on.

**Comment by juchowan** [comment]
Site was manually registered in ND. With mso_site we are just trying to change it to "managed" and assign site ID

**Comment by anvitha-jain** [comment]
@juchowan
Let me re-verify from my end and get back to you on this.

**Comment by anvitha-jain** [comment]
> Site was manually registered in ND. With mso_site we are just trying to change it to "managed" and assign site ID

@juchowan , were you able to change it to managed on UI (by manually making changes) ?
