### ISSUE TITLE
Updating a sub-attribute of a template in `mso_schema` fails when `template_type` is not specified in the Terraform config.

### ISSUE THREAD

**Issue by andbyrne** [CiscoDevNet/terraform-provider-mso#232]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.5.3
on darwin_arm64
+ provider registry.terraform.io/ciscodevnet/mso v0.11.0

### MSO version

* NDO V 4.1.2e

### Affected Resource(s)

* mso_schema

### Expected Behavior

When a `description` attribute is added to an existing template in a `mso_schema` resource, the description will be updated.

### Actual Behavior

The provider attempts to remove and create a replacement template block.

Note: This also applies when adding new template blocks to an existing `mso_schema` resource.

### Steps to Reproduce

1. Define the schema with one template and no description:

```hcl
resource "mso_schema" "schema" {
    name = "Bug"

    template {
        name          = "Template1"
        display_name  = "Template1"
        tenant_id     = "64b8e6f789c60aeac323c7c5"
    }
}
```

2. `terraform apply`

3. Update the template to include a description:

```hcl
resource "mso_schema" "schema" {
    name = "Bug"

    template {
        name          = "Template1"
        display_name  = "Template1"
        tenant_id     = "64b8e6f789c60aeac323c7c5"
        description   = "bug"
    }
}
```

4. `terraform plan`

```
  # module.ndo.mso_schema.schema will be updated in-place
  ~ resource "mso_schema" "schema" {
        id   = "64b8e6fa89c60aeac323c7c8"
        name = "Bug"

      - template {
          - display_name  = "Template1" -> null
          - name          = "Template1" -> null
          - template_type = "aci_multi_site" -> null
          - tenant_id     = "64b8e6f789c60aeac323c7c5" -> null
        }
      + template {
          + description   = "bug"
          + display_name  = "Template1"
          + name          = "Template1"
          + template_type = (known after apply)
          + tenant_id     = "64b8e6f789c60aeac323c7c5"
        }
    }
```

**Comment by lhercot** [comment]
@andbyrne  Does it actually replace it or the plan tells you that the diff is this block is replace by this block?

I am asking as to my understanding, blocks (TypeSet) differences are based on the hash of the whole object so if any attribute change, it will show it as a replacement of the whole block as shown here. But when I read the code of the update function for this resource, it will only PATCH the description in this case.

**Comment by andbyrne** [comment]
Here is sanitized debug output when it fails to apply the above change:

```
2023-07-24T09:30:38.716+1000 [WARN]  Provider "registry.terraform.io/ciscodevnet/mso" produced an invalid plan for module.ndo.mso_schema.schema["Bug"], but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .template_name: planned value cty.StringVal("") for a non-computed attribute
      - .tenant_id: planned value cty.StringVal("") for a non-computed attribute
module.ndo.mso_schema.schema["Bug"]: Modifying... [id=64b8e6fa89c60aeac323c7c8]
2023-07-24T09:30:38.716+1000 [INFO]  Starting apply for module.ndo.mso_schema.schema["Bug"]
2023-07-24T09:30:38.717+1000 [DEBUG] module.ndo.mso_schema.schema["Bug"]: applying the planned Update change
2023-07-24T09:30:38.717+1000 [DEBUG] provider.terraform-provider-mso_v0.11.0: 2023/07/24 09:30:38 [DEBUG] Schema: Beginning Update
2023-07-24T09:30:38.928+1000 [ERROR] vertex "module.ndo.mso_schema.schema[\"Bug\"]" error: Template type cannot be changed.
2023-07-24T09:30:38.928+1000 [DEBUG] cloud/state: state read serial is: 44; serial is: 44
2023-07-24T09:30:38.928+1000 [DEBUG] cloud/state: state read lineage is: 8e38bbc5-7cfa-e8e6-1e38-b8bdb83a3613; lineage is: 8e38bbc5-7cfa-e8e6-1e38-b8bdb83a3613
╷
│ Error: Template type cannot be changed.
│ 
│   with module.ndo.mso_schema.schema["Bug"],
│   on ../../../terraform-mso-nac-ndo/ndo_schemas.tf line 58, in resource "mso_schema" "schema":
│   58: resource "mso_schema" "schema" {
│ 
╵
2023-07-24T09:30:40.499+1000 [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = error reading from server: EOF"
2023-07-24T09:30:40.502+1000 [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/ciscodevnet/mso/0.11.0/darwin_arm64/terraform-provider-mso_v0.11.0 pid=10470
2023-07-24T09:30:40.502+1000 [DEBUG] provider: plugin exited
```

If I initially create the template with a description and then try to change it, the same issue occurs. However if I add a second template it works fine as long as the existing template has a description set.

There appears to be an issue with the way the description attribute was implemented in https://github.com/CiscoDevNet/terraform-provider-mso/commit/b9c7f0c33d5f094ca316819d81b4339ee14d7b99.

**Comment by shrsr** [comment]
@andbyrne 
1. Lionel (@lhercot ) already addressed the initial comment in the issue.

2. For your most recent comment - 
The attribute **template_type** is implicitly being updated and **description** is explicitly being updated. 
It is the former that is causing the issue and not the latter.  Our provider's update function does not allow changing the **template_type**.  Though you're not updating **template_type**, this attribute is Computed in our provider code. If this attribute is left empty while creating the resource, it will be populated with whatever value NDO assigns it. Whilst you're trying to update the **description**, Terraform is also trying to update **template_type** from "aci_multi_site"  to "known after apply" because your config. does not have a value for it.

I believe you should not see an issue updating the **description** if you configure **template_type** as well.
Our team will address the issue related to **template_type** being updated when it is not configured.

**Comment by andbyrne** [comment]
Unfortunately it does not matter if I specify the `template_type` or not. The only way to reliably get the `mso_schema` resource to work is to set a `description` on every template that's added. Only then can you add subsequent templates without Terraform trying to remove the originals.

**Comment by shrsr** [comment]
@andbyrne In the code snippet below -
```
~ resource "mso_schema" "schema" {
        id   = "64b8e6fa89c60aeac323c7c8"
        name = "Bug"

      - template {
          - display_name  = "Template1" -> null
          - name          = "Template1" -> null
          - template_type = "aci_multi_site" -> null
          - tenant_id     = "64b8e6f789c60aeac323c7c5" -> null
        }
      + template {
          + description   = "bug"
          + display_name  = "Template1"
          + name          = "Template1"
          + template_type = (known after apply)
          + tenant_id     = "64b8e6f789c60aeac323c7c5"
        }
    }
```
Even though Terraform shows a plan where the template block is marked for removal and addition again with the changed sub-attributes in the block, the code in the Provider back-end uses a PATCH operation. The Template1 above is actually updated and not removed or added again.
It is the property of TypeSet in Terraform showing the above oddity. Please see the comment in: https://discuss.hashicorp.com/t/typeset-is-not-picking-up-correct-changes/23735 by a HashiCorp developer.

Scenario ->
Create a template using the above block in Terraform. Add a VRF to that template, this time in the UI.
Make a change to one of the sub-attributes such as description for the template back in Terraform and apply it.
If you check the template in the UI, the VRF would still be associated to it with the updated description of the template.

**Comment by andbyrne** [comment]
Thank you for the clarification @shrsr

In this case, I will await your fix to the optional `template_type` attribute not being specified which should address this issue.
