### ISSUE TITLE
Add NDO descriptions for VRF, ANP, etc.

### ISSUE THREAD

**Issue by balnovak** [CiscoDevNet/terraform-provider-mso#246]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The TF provider currently does not support the descriptions for the following objects (although the REST API does):

VRF
ANP
CONTRACT
FILTER
EXTERNAL EPG
L3OUT

### New or Affected Resource(s) + MSO Class(es):

Affected resources:

- VRF: [mso_schema_template_vrf](https://registry.terraform.io/providers/CiscoDevNet/mso/0.11.1/docs/resources/schema_template_vrf)
- ANP: [mso_schema_template_anp](https://registry.terraform.io/providers/CiscoDevNet/mso/0.11.1/docs/resources/schema_template_anp)
- CONTRACT: [mso_schema_template_contract](https://registry.terraform.io/providers/CiscoDevNet/mso/0.11.1/docs/resources/schema_template_contract)
- FILTER: [mso_schema_template_contract_filter](https://registry.terraform.io/providers/CiscoDevNet/mso/0.11.1/docs/resources/schema_template_contract_filter)
- External EPG: [mso_schema_template_external_epg](https://registry.terraform.io/providers/CiscoDevNet/mso/0.11.1/docs/resources/schema_template_external_epg)
- L3out: [mso_schema_template_l3out](https://registry.terraform.io/providers/CiscoDevNet/mso/0.11.1/docs/resources/schema_template_l3out)

**Comment by akinross** [comment]
@balnovak Thank you for opening the issue. I have added it to the todo items.
