### ISSUE TITLE
Issue getting Contract Information using MSO Terraform Provider

### ISSUE THREAD

**Issue by malriddell** [CiscoDevNet/terraform-provider-mso#263]
MSO Terraform Provider version 0.8.1
When a contract is created in the NSO and the "save" button is pressed, I see the contract appear in the raw schema(pulled via a REST CALL) under the '/templates/' and '/sites/' sections(the two primary sections of the schema).  When I create contracts via Terraform Only, I never see those contracts under '/sites/', and I don't see '/sites/' noted anywhere for contract addition in the terraform MSO provider source code.

**Comment by akinross** [comment]
Hi @malriddell,

What version of NDO/MSO are you running? 
Could you share your terraform code?

**Comment by akinross** [comment]
Hi @malriddell, any updates already?

**Comment by akinross** [comment]
Hi @malriddell , any updates already or can we close the issue?

**Comment by akinross** [comment]
Closing the issue due to no response, in case you have any follow-up please let us know then we can reopen the issue.
