### ISSUE TITLE
cannot create ndo template resource

### ISSUE THREAD

**Issue by ktorkmen** [CiscoDevNet/terraform-provider-mso#269]
mso_schema_template.template: Creating...
╷
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to mso_schema_template.template, provider "provider[\"registry.terraform.io/hashicorp/mso\"]"
│ produced an unexpected new value: Root resource was present, but now absent.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
v1.0.0

### MSO version

* V 2.3(1c)

### APIC version and APIC Platform for Site Level Resources

* V 5.2(8h) and on-prem/cloud-aws/cloud-azure/all.

### Affected Resource(s)

* mso_schema_template

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by ktorkmen** [comment]
Hello @akinross ,
Thanks for your answer.
What I noticed is that terraform keeps creating the template. So I have one schema with a lot of templates with the same name.
1. Tried with 1.1.0 and it is the same issue.
2. Configuration:


resource "mso_schema_template" "dcc_aac_template" {
  schema_id     = mso_schema.dcc_aac_schema.id
  name          = "DCC AAC Template"
  display_name  = "DCC AAC Template"
  tenant_id     = resource.mso_tenant.dcc_aac_tenant.id
  template_type = "aci_multi_site"
}



3. This is the complete output:

terraform init

Initializing the backend...

Initializing provider plugins...
- Finding latest version of hashicorp/mso...
- Installing hashicorp/mso v1.1.0...
- Installed hashicorp/mso v1.1.0 (unauthenticated)

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

╷
│ Warning: Incomplete lock file information for providers
│
│ Due to your customized provider installation methods, Terraform was forced to calculate lock file checksums locally for the
│ following providers:
│   - hashicorp/mso
│
│ The current .terraform.lock.hcl file only includes checksums for linux_amd64, so Terraform running on another platform will fail
│ to install these providers.
│
│ To calculate additional checksums for another platform, run:
│   terraform providers lock -platform=linux_amd64
│ (where linux_amd64 is the platform to generate)
╵

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.




data.mso_site.mysite: Reading...
data.mso_user.tf_user: Reading...
data.mso_user.tf_user: Read complete after 0s [id=a2fb76046a2b45f9d01bf29c9a5507244bd4402d813074f9cbf01b10c77b3710]
data.mso_site.USCSF01: Read complete after 0s [id=64535bed6a373804f68d815a]
mso_tenant.dcc_aac_tenant: Refreshing state... [id=6629265620000068b38e4413]
mso_schema.dcc_aac_schema: Refreshing state... [id=662926561f00007ea94be2ac]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following
symbols:
  + create
  ~ update in-place

Terraform will perform the following actions:

  # mso_schema.dcc_aac_schema will be updated in-place
  ~ resource "mso_schema" "dcc_aac_schema" {
        id   = "662926561f00007ea94be2ac"
        name = "dcc_aac_schema"

      - template {
          - display_name  = "DCC AAC Template" -> null
          - name          = "DCCAACTemplate" -> null
          - template_type = "aci_multi_site" -> null
          - tenant_id     = "6629265620000068b38e4413" -> null
        }
      + template {
          + description   = (known after apply)
          + display_name  = "DCC AAC Template"
          + name          = "DCC AAC Template"
          + template_type = "aci_multi_site"
          + tenant_id     = "6629265620000068b38e4413"
        }
    }

  # mso_schema_template.dcc_aac_template will be created
  + resource "mso_schema_template" "dcc_aac_template" {
      + description   = (known after apply)
      + display_name  = "DCC AAC Template"
      + id            = (known after apply)
      + name          = "DCC AAC Template"
      + schema_id     = "662926561f00007ea94be2ac"
      + template_type = "aci_multi_site"
      + tenant_id     = "6629265620000068b38e4413"
    }

  # mso_tenant.dcc_aac_tenant will be updated in-place
  ~ resource "mso_tenant" "dcc_aac_tenant" {
        id                = "6629265620000068b38e4413"
        name              = "tn-dcc-aac-tenant"
        # (3 unchanged attributes hidden)

      - user_associations {
          - user_id = "48d105bdfbc49a5fcf39a10b961386e61dfe40085cb0315d818b761c5735dafa" -> null
        }

        # (2 unchanged blocks hidden)
    }

Plan: 1 to add, 2 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

mso_tenant.dcc_aac_tenant: Modifying... [id=6629265620000068b38e4413]
mso_tenant.dcc_aac_tenant: Modifications complete after 1s [id=6629265620000068b38e4413]
mso_schema.dcc_aac_schema: Modifying... [id=662926561f00007ea94be2ac]
mso_schema.dcc_aac_schema: Modifications complete after 0s [id=662926561f00007ea94be2ac]
mso_schema_template.dcc_aac_template: Creating...
╷
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to mso_schema_template.dcc_aac_template, provider "provider[\"registry.terraform.io/hashicorp/mso\"]"
│ produced an unexpected new value: Root resource was present, but now absent.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.

**Comment by ktorkmen** [comment]
I created the templates using the template resource and part of the schema, that is why it was not working.

**Comment by akinross** [comment]
Hi @ktorkmen,

Not sure I follow exactly what resolved your issue or what your initial issue exactly was, but good it is resolved.

**Comment by ktorkmen** [comment]
The issue is when you create the mso_schema_template resource, separately it throws that error.
So, instead, just create the template under mso_schema
