### ISSUE TITLE
data mso_user fail - Error: invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by PhilipWhiteside** [CiscoDevNet/terraform-provider-mso#27]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

* v1.0.0

### MSO version

* V 3.3.1e
* Physical Nexus Dashboard: 2.0(2g)

### APIC version and APIC Platform for Site Level Resources

* V 4.2(6d) on-prem

### Affected Resource(s)

* mso_user (data)

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    mso = {
      source  = "CiscoDevNet/mso"
      version = "0.1.5"
    }
  }
}

variable "mso_username" {
  type      = string
  sensitive = true
  default   = "pwhitesi"
}
variable "mso_password" {
  type      = string
  sensitive = true
}
variable "mso_hostname" {
  type      = string
  sensitive = true
}
variable "mso_insecure" {
  type      = string
  sensitive = true
  default   = "true"
}

provider "mso" {
  username = var.mso_username
  password = var.mso_password
  url      = var.mso_hostname
  insecure = var.mso_insecure
}

data "mso_user" "myself" {
  username = "pwhitesi"
}
```

### Debug Output

https://gist.github.com/PhilipWhiteside/60a3ef115b980767b281be0c0c5c3768

### Expected Behavior

Get the user id of the user. 

I know the user works and exists because I can create resources with the same config, without this `data "mso_user"` block. 

### Actual Behavior

Fails to get user information, 404 not found on API

```
│ Error: invalid character '<' looking for beginning of value
│ 
│   with data.mso_user.myself,
│   on main.tf line 1, in data "mso_user" "myself":
│    1: data "mso_user" "myself" {
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

This user is an AD user, via ISE, with that ISE being the default login domain within Nexus Dashboard. 

### References

* #0000

**Comment by anvitha-jain** [comment]
This issue is resolved, and the changes are in #55 . This will be soon be available in the next release.
