### ISSUE TITLE
mso_schema_site_anp_epg_bulk_staticport different order of imported static ports

### ISSUE THREAD

**Issue by juchowan** [CiscoDevNet/terraform-provider-mso#301]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In the mso_schema_site_anp_epg_bulk_staticport the static_ports block is created dynamically.
For the existing epg and static ports we import configuration that was previously done manually, and the static port blocks are created in the order in which they are returned by NDO API. 
For our terraform code we use a for_each loop to create the static ports dynamically (existing and new ones), and the for_each loop will create these static_port blocks in an order based on the key of list that we create by combining pod ids, node ids, ports etc (to have a uniqe key per each element). This order will be done deterministically based on the ports configured, and will not always match the order of ports that were created manually and are returned from NDO API. This is causing terraform to try to modify each bulk and reorder elements.

### New or Affected Resource(s) + MSO Class(es):

* mso_schema_site_anp_epg_bulk_staticport

### MSO version

* V 4.2.3k

### APIC version and APIC Platform for Site level Resources

* V all

### References

* #0000

**Comment by lhercot** [comment]
This is the expected behavior as we consider that the order in the API/UI should be maintained and that changing the order in terraform is the user communicating his intent of wanting the order to be different in NDO.

**Comment by juchowan** [comment]
Understand that we want to match the UI. What is then the correct way to create these blocks to be generated dynamically and match the order of GUI?

**Comment by lhercot** [comment]
In your case, you are trying to import an existing config so if you don't want any change to appear on the next `terraform plan` you will want to map the current order in the NDO.

If you are in a greenfield scenario (new EPG for example) the order provided in terraform will be respected.

**Comment by juchowan** [comment]
Thanks
