### ISSUE TITLE
panic: runtime error: index out of range [3] with length 0

### ISSUE THREAD

**Issue by qbeusz** [CiscoDevNet/terraform-provider-mso#38]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.0.3
on linux_amd64
+ provider registry.terraform.io/ciscodevnet/mso v0.2.1

### MSO version

* V 3.3(1e)

### APIC version and APIC Platform for Site Level Resources

* V 5.2(1g)  on-prem
* V 5.1(2e)  cloud-azure

### Affected Resource(s)

terraform import mso_schema_template_anp_epg.LAB_EPG_FRONTEND 60faccd43a00008c452f97ba/template/ONPREM/anp/LAB_ACI_AP1_MSO/epg/LAB_EPG_FRONTEND

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Debug Output

mso_schema_template_anp_epg.LAB_EPG_FRONTEND: Importing from ID "60faccd43a00008c452f97ba/template/ONPREM/anp/LAB_ACI_AP1_MSO/epg/LAB_EPG_FRONTEND"...
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ImportResourceState call. The plugin logs may contain more
│ details.
╵

Stack trace from the terraform-provider-mso_v0.2.1 plugin:

panic: runtime error: index out of range [3] with length 0

goroutine 16 [running]:
github.com/terraform-providers/terraform-provider-mso/mso.resourceMSOSchemaTemplateAnpEpgImport(0xc0005882a0, 0x10cf780, 0xc0005881c0, 0x1b, 0xc000338a88, 0x7f67290ac101, 0x0, 0x0)
        github.com/terraform-providers/terraform-provider-mso/mso/resource_mso_schema_template_anp_epg.go:188 +0x19ec
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).ImportState(0xc000182900, 0xc0002d1ad0, 0xc00003eea0, 0x51, 0x7c25b4, 0xc0002ee150, 0x70, 0x70, 0x10be240)
        github.com/hashicorp/terraform-plugin-sdk@v1.14.0/helper/schema/provider.go:390 +0x28b
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ImportResourceState(0xc00000e628, 0x13a7a80, 0xc000418ba0, 0xc000440900, 0xc00000e628, 0xc000418ba0, 0xc000409b78)
        github.com/hashicorp/terraform-plugin-sdk@v1.14.0/internal/helper/plugin/grpc_provider.go:953 +0xec
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ImportResourceState_Handler(0x10ed000, 0xc00000e628, 0x13a7a80, 0xc000418ba0, 0xc0005601e0, 0x0, 0x13a7a80, 0xc000418ba0, 0xc0002ee150, 0x70)
        github.com/hashicorp/terraform-plugin-sdk@v1.14.0/internal/tfplugin5/tfplugin5.pb.go:3323 +0x217
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000001680, 0x13b27a0, 0xc000156300, 0xc000180a00, 0xc000088bd0, 0x1b195b8, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.27.1/server.go:1024 +0x501
google.golang.org/grpc.(*Server).handleStream(0xc000001680, 0x13b27a0, 0xc000156300, 0xc000180a00, 0x0)
        google.golang.org/grpc@v1.27.1/server.go:1313 +0xd3d
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000038260, 0xc000001680, 0x13b27a0, 0xc000156300, 0xc000180a00)
        google.golang.org/grpc@v1.27.1/server.go:722 +0xa1
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.27.1/server.go:720 +0xa1

Error: The terraform-provider-mso_v0.2.1 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by shrsr** [comment]
@qbeusz I'm unable to reproduce the issue at my end.
Can you please share the terraform configuration file that you used for this?

**Comment by shrsr** [comment]
@qbeusz I was able to reproduce the issue. I have fixed the issue and you should be able to use the import function after the next release.
