### ISSUE TITLE
Unable to handle multiple new mso_schema_site in configuration 

### ISSUE THREAD

**Issue by andreassb** [CiscoDevNet/terraform-provider-mso#41]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.0.4
on darwin_amd64
+ provider registry.terraform.io/ciscodevnet/mso v0.2.1

### MSO version

* V 3.3(1e)
* V 3.4(1a)

### APIC version and APIC Platform for Site Level Resources

* V 5.1(1h) on-prem

### Affected Resource(s)

* mso_schema_template
* mso_schema_site

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    mso = {
      source = "CiscoDevNet/mso"
      version = "0.2.1"
    }
  }
}

provider "mso" {
    username = "admin"
    password = "C1sco12345"
    url      = "https://198.18.133.100/"
    insecure = true
    platform = "nd"
}

variable "site_id" {
  type = string
  default = "611cdd33c5dba78e53c3ffa5"
}

## Tenants

resource "mso_tenant" "Tenant1" {
  name = "Tenant1"
  display_name = "Tenant1"
  site_associations {
    site_id = var.site_id
  }
}

### APAC schemas for application profiles and contracts

resource "mso_schema" "APAC-Apps01" {
  name          = "APAC-Apps01"
  template_name = "Template1"
  tenant_id     = mso_tenant.Tenant1.id
}
resource "mso_schema_site" "APAC-Apps01-Template1" {
  schema_id       =  mso_schema.APAC-Apps01.id
  site_id         =  var.site_id
  template_name   =  "Template1"
}

resource "mso_schema_template" "APAC-Apps01-Template2" {
  schema_id     = mso_schema.APAC-Apps01.id
  name          = "Template2"
  display_name  = "Template2"
  tenant_id     = mso_tenant.Tenant1.id
}
resource "mso_schema_site" "APAC-Apps01-Template2_site" {
  schema_id       =  mso_schema.APAC-Apps01.id
  site_id         =  var.site_id
  template_name   =  "Template2"
}


resource "mso_schema_template" "APAC-Apps01-Template3" {
  schema_id     = mso_schema.APAC-Apps01.id
  name          = "Template3"
  display_name  = "Template3"
  tenant_id     = mso_tenant.Tenant1.id
}
resource "mso_schema_site" "APAC-Apps01-Template3_site" {
  schema_id       =  mso_schema.APAC-Apps01.id
  site_id         =  var.site_id
  template_name   =  "Template3"
}


resource "mso_schema_template" "APAC-Apps01-Template4" {
  schema_id     = mso_schema.APAC-Apps01.id
  name          = "Template4"
  display_name  = "Template4"
  tenant_id     = mso_tenant.Tenant1.id
}
resource "mso_schema_site" "APAC-Apps01-Template4_site" {
  schema_id       =  mso_schema.APAC-Apps01.id
  site_id         =  var.site_id
  template_name   =  "Template4"
}

```

### Debug Output

1st attempt with terraform apply results in 5 errors
 - 2 x Provider produced inconsistent result after apply
 - 3 x "Bad Request: Patch Failed, Received: None.get exception while trying to update schema"{}
 - Debug output: https://gist.github.com/andreassb/ec6fc3b84ab0cdc54064d6673408adf2

2nd attempt with terraform apply results in 4 errors
 - 2 x Provider produced inconsistent result after apply
 - 2 x "Bad Request: Patch Failed, Received: None.get exception while trying to update schema"{}
 - Debug output: https://gist.github.com/andreassb/0aac060e83983d34397e1fe629d727f8

3rd attempt with terraform apply results in 3 errors
 - 1 x Provider produced inconsistent result after apply
 - 2 x "Bad Request: Patch Failed, Received: None.get exception while trying to update schema"{}
 - Debug output: https://gist.github.com/andreassb/820c8d5aeed72ea6364831cff490fead

4th attempt with terraform apply results in 2 errors
 - 1 x Provider produced inconsistent result after apply
 - 1 x "Bad Request: Patch Failed, Received: None.get exception while trying to update schema"{}
 - Debug output: https://gist.github.com/andreassb/cfccd06b2d45d438580287fb1e63f36e

5th attempt with terraform apply results in 1 error
 - 1 x "Bad Request: Patch Failed, Received: None.get exception while trying to update schema"{}
 - Debug output: https://gist.github.com/andreassb/43a4fced5f2a7d0944f7f6574fd0209b

6th attempt succeeds.
 - Debug output: https://gist.github.com/andreassb/38fec05e6e527782cdd74c092cd0e983

### Expected Behavior

All configuration should successfully be applied in just 1 attempt.

### Actual Behavior

Only part of the configuration is applied during each run.

### Steps to Reproduce

1. `terraform apply` multiple times until success.
2. Using "terraform apply -parallelism=1" reduces the number of times you have to apply. 

### Important Factoids

I suspect an order-of-operations problem.

**Comment by andreassb** [comment]
After the final and successful "terraform apply" it is not possible to remove the template site associations again:

Error: "Bad Request: Patch Failed, Received: None.get exception while trying to update schema"{}

**Comment by lhercot** [comment]
First use -parallelism=1 as you mentioned as there is an API concurrency issue we are working with MSO Engineering to address.

Secondly, on all your mso_schema_site resources (except Template1), you have to have an implicit or explicit dependency to the schema_template.

Simplest is to do the explicit so change your resource definition to:
```
resource "mso_schema_site" "APAC-Apps01-Template2_site" {
  schema_id       =  mso_schema.APAC-Apps01.id
  site_id         =  var.site_id
  template_name   =  mso_schema_template.APAC-Apps01-Template2.name
}
```

By referencing the name via the mso_schema_template resource, you avoid repetition of the name so a single place to change it and you also create the implicit dependency that Terraform need to determine the right order of operation.

Let me know if this fixes most of your issues.

**Comment by lhercot** [comment]
Closing this issue. If the fix provided does not work, feel free to open a new issue.
