### ISSUE TITLE
mso_schema_template_contract filter_relationships only allows one single filter_relationship

### ISSUE THREAD

**Issue by andreassb** [CiscoDevNet/terraform-provider-mso#42]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.0.4
on darwin_amd64
+ provider registry.terraform.io/ciscodevnet/mso v0.2.1

### MSO version

* V 3.3(1e)

### APIC version and APIC Platform for Site Level Resources

* V 5.1(1h) on-prem

### Affected Resource(s)

* mso_schema_template_contract

### Terraform Configuration Files

```hcl

resource "mso_schema_template_contract" "Contract1" {
  schema_id = "SchemaId"
  template_name = "Template1"
  contract_name = "Contract1"
  display_name = "Contract1"
  filter_type = "bothWay"
  scope = "context"
  filter_relationships = [
    {
      filter_schema_id = "SchemaId"
      filter_template_name = "Template1"
      filter_name = "Filter1"
    },
    {
      filter_schema_id = "SchemaId"
      filter_template_name = "Template1"
      filter_name = "Filter2"
    }
  ]
  directives = ["none"]
}
```

### Debug Output

```
Inappropriate value for attribute "filter_relationships": map of string required.
```

### Expected Behavior

Multiple filter_relationships should be configured, just like it is possible through GUI and API. The module name is plural, and so is the corresponding feature expected to be.

### Actual Behavior

Unable to define more than a single filter_relationship.

### Steps to Reproduce

1. `terraform apply`

an alternative way to see the issue is to import a contract from MSO with multiple filter_relationsships. Only 1 of them will get imported.
`terraform import mso_schema_template_contract.Contract1 612607f92e0000a501c781ae/template/Template1/contracts/Contract1`

**Comment by lhercot** [comment]
You can use today mso_schema_template_contract_filter to add additional contracts to it.
On top of that, we have implemented a new attribute filter_relationship which is a block and will allow you to define more than 1. This will be available in the next release. We have added a deprecation warning for the filter_relationships attribute in the same release.
