### ISSUE TITLE
mso_schema_site_l3out, resource and datasources are are missing (DCNE-149)

### ISSUE THREAD

**Issue by anvitha-jain** [CiscoDevNet/terraform-provider-mso#54]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Resource and data source files needs to be created for  site L3out (schema_site_l3out)

### New or Affected Resource(s) + MSO Class(es):

* mso_schema_site_l3out

* #0000

**Comment by akinross** [comment]
recent version of NDO solves this directly and this resource is not needed
