### ISSUE TITLE
doc bug: mso_template_bd should be "mso_schema_template_bd"

### ISSUE THREAD

**Issue by mihiguch** [CiscoDevNet/terraform-provider-mso#58]
It seems doc bug.
https://registry.terraform.io/providers/CiscoDevNet/mso/latest/docs/resources/template_bd
We have "mso_template_bd" under Resources on the left side, but it's actually “mso_schema_template_bd”.

**Comment by anvitha-jain** [comment]
The changes have been made and will be available in next version.
