### ISSUE TITLE
terraform destroy is failed if it contains BD and VRF deletions together.

### ISSUE THREAD

**Issue by mihiguch** [CiscoDevNet/terraform-provider-mso#62]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v1.0.7

### MSO version
NDO version 3.5.0.175

### APIC version and APIC Platform for Site Level Resources
APIC: 5.2(2.138a)
It shouldn't be relevant as it's just a creation of filter in schema.

### Affected Resource(s)
NDO version 3.5.0.175

### Terraform Configuration Files
**main.tf has resources to create a VRF and a BD in the VRF. "terraform apply" works fine but "terraform destroy" doesn't work. It seems trying to delete the VRF before deleting BD. Please see "Actual Behavior" section.
(If it's just a BD deletion, it works fine.)**

resource "mso_schema_template_vrf" "vrf_obj" {
    schema_id     = mso_schema.schema_obj.id
    template      = mso_schema.schema_obj.template_name
    name          = var.vrf
    display_name  = var.vrf
}

resource "mso_schema_template_bd" "bd_obj" {
    schema_id               = mso_schema.schema_obj.id
    template_name           = mso_schema.schema_obj.template_name
    name                    = "BD-test"
    display_name            = "BD-test"
    vrf_name                = mso_schema_template_vrf.vrf_obj.name
    layer2_stretch          = "true"
    intersite_bum_traffic   = "true"
    optimize_wan_bandwidth  = "true"
}

### Expected Behavior
VRF deletion should happen after BD is deleted

### Actual Behavior
**It seems trying to delete VRF before deleting the BD in the VRF.**

mso_schema_template_bd.bd_obj: Destroying... [id=BD-test]
mso_schema_template_bd.bd_obj: Destruction complete after 1s
mso_schema_template_anp_epg.end_point_groups: Destruction complete after 1s
mso_schema_template_vrf.vrf_obj: Destroying... [id=vrf1]
mso_schema_template_anp.anp1: Destroying... [id=App1]
mso_schema_template_anp.anp1: Destruction complete after 1s
╷
│ Error: "Bad Request: Patch Failed, Received: BD 'BD-test' in template stretched-template is associated to VRF vrf1 in template stretched-template in schema mihiguch-test_schema which is not valid exception while trying to update schema"{}
│ 

### Steps to Reproduce
terraform destroy

**Comment by shrsr** [comment]
Closing this issue because it is resolved with -
terraform apply -parallelism=1
terraform destroy -parallelism=1
