### ISSUE TITLE
Doc bug: mso_schema_template_service_graph

### ISSUE THREAD

**Issue by mihiguch** [CiscoDevNet/terraform-provider-mso#64]
https://registry.terraform.io/providers/CiscoDevNet/mso/latest/docs/resources/schema_template_service_graph

It should provide acceptable value for service_node_type. It seems it has to be either "firewall", "load-balancer" or "other".
> service_node_type - (Required) Type of Service Node attached to this Graph.

**Comment by anvitha-jain** [comment]
These changes are made and will be available in next release.
