### ISSUE TITLE
Terraform mso provider support for vendor = "azure"

### ISSUE THREAD

**Issue by soumukhe** [CiscoDevNet/terraform-provider-mso#75]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Support for cloud provider azure  for Terraform with Nexus Dashboard Orchestrator ( NDO )

Currently, it seems that only aws cloud is supported.   Is azure is in the works ?

**Comment by lhercot** [comment]
We already support some of the base Azure capabilities. Let me know what you are looking for and we can look to prioritize them.

**Comment by lhercot** [comment]
I will be closing this issue as this ask is too generic and we already support some of those feature. Please feel free to open more specific issues on those capabilities if we are missing any.
