### ISSUE TITLE
MSO Provider, sites have to be added to Template one at a time, else it errors

### ISSUE THREAD

**Issue by soumukhe** [CiscoDevNet/terraform-provider-mso#76]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

# Versions
ND: 2.1.1d
NDO : 3.5.1e
Terraform: v1.0.10
mso_plugin: v0.3.2

# Description of problem:
In a shared Template, when you try to associated more than 1 site to the same shared template (in different resource blocks of "mso_schema_site"), it throws an error.   

If you put the config of 1 site, then do terraform apply,  then add one more site, then do terraform apply and continue that way then it works.

# example below:
#  Associate Schema / template with Site

resource "mso_schema_site" "site1" {
  schema_id     = mso_schema.schema1.id
  site_id       = data.mso_site.site1.id
  template_name = var.schema.template_name1
}

resource "mso_schema_site" "site2" {
  schema_id     = mso_schema.schema1.id
  site_id       = data.mso_site.site2.id
  template_name = var.schema.template_name1
}

resource "mso_schema_site" "site3" {
  schema_id     = mso_schema.schema1.id
  site_id       = data.mso_site.site3.id
  template_name = var.schema.template_name1
}

# when doing a terraform apply for the above configuration, the output is as such:
Plan: 5 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.mso.mso_tenant.tenant: Creating...
module.mso.mso_tenant.tenant: Creation complete after 0s [id=617f68d8210000472048e161]
module.mso.mso_schema.schema1: Creating...
module.mso.mso_schema.schema1: Creation complete after 1s [id=617f68d8210000462048e162]
module.mso.mso_schema_site.site1: Creating...
module.mso.mso_schema_site.site3: Creating...
module.mso.mso_schema_site.site2: Creating...
module.mso.mso_schema_site.site1: Creation complete after 0s [id=614ffb40562ca8085d6bacc8]
module.mso.mso_schema_site.site2: Creation complete after 0s [id=61750885f5b04bc82bf7a15c]
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to module.mso.mso_schema_site.site3, provider "module.mso.provider[\"registry.terraform.io/ciscodevnet/mso\"]" produced an unexpected new value:
│ Root resource was present, but now absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.

# also, if you do terraform apply multiple times, it finally takes it

**Comment by soumukhe** [comment]
# When I extend this further to create VRF/BD/EPG,  I have to do a terraform apply 6 times for the configuration to fully take:
aciadmin@ubuntu-jump:~/NDDemo/Terraform/main$ cat ApplyTF6.sh 
#!/bin/sh
terraform apply --auto-approve
sleep 2
terraform apply --auto-approve
sleep 2
terraform apply --auto-approve
sleep 2
terraform apply --auto-approve
sleep 2
terraform apply --auto-approve
sleep 2
terraform apply --auto-approve

# Similarly For the configuration to fully destroy I have to do terraform destroy 3 times

attaching resources.tf.txt file because .tf extension cannot be uploaded here

[resources.tf.txt](https://github.com/CiscoDevNet/terraform-provider-mso/files/7450883/resources.tf.txt)
es

**Comment by lhercot** [comment]
Please use -parallelism=1 with any apply and destroy and let me know if that solves the issue.

**Comment by soumukhe** [comment]
# Thank You Lionel.  I tried  '-parallelism=1" flag and also had to adjust the terraform script a bit.  However, I still have to do twice when destroying.  

incidentally,  terraform destroy directly does not seem to support '-parallelism=1" flag,  however, terraform apply -destroy does.

To make it simpler I set env varialble by: export TF_CLI_ARGS_apply='-parallelism=1" 
 then I can just use terraform apply    and terraform apply -destroy

# Details of what I did

I had to readjust the way template_name is read into resource "mso_schema_site" for all the sites.  Instead of reading directly from variable by:  template_name = var.schema.template_name1,  I defined a data source right after creation of schema as shown below:

# create template and associate with Schema
resource "mso_schema" "schema1" {
  name                   = var.schema.schema1
  template_name   = var.schema.template_name1
  tenant_id     = mso_tenant.tenant.id
}

# define data source for use in later resources
data "mso_schema_template" "template1" {
  name           = var.schema.template_name1
  #name        = mso_schema_template.template1.name
  schema_id = mso_schema.schema1.id
}

#  Associate Schema / template with Site using template name defined from data instead of from variable 
resource "mso_schema_site" "site1" {
  depends_on = [mso_schema.schema1]
  schema_id     = mso_schema.schema1.id
  site_id       = data.mso_site.site1.id
  #template_name = var.schema.template_name1
  template_name = data.mso_schema_template.template1.name

}

resource "mso_schema_site" "site2" {
  schema_id     = mso_schema.schema1.id
  site_id       = data.mso_site.site2.id
  #template_name = var.schema.template_name1
  template_name = data.mso_schema_template.template1.name
}

resource "mso_schema_site" "site3" {
  schema_id     = mso_schema.schema1.id
  site_id       = data.mso_site.site3.id
  #template_name = var.schema.template_name1
  template_name = data.mso_schema_template.template1.name
}

# Results of terraform apply:
terraform apply          # note that  export TF_CLI_ARGS_apply='-parallelism=1"   was set initially
...
Apply complete! Resources: 15 added, 0 changed, 0 destroyed.

# Results of terraform apply -destroy   (1st try)

module.mso.mso_schema_site_vrf.aws_site: Destroying... [id=vrf1]
module.mso.mso_schema_site.site2: Destroying... [id=61750885f5b04bc82bf7a15c]
module.mso.mso_schema_site.site2: Destruction complete after 0s
╷
│ Error: "Resource Not Found: site with site ID : 61747c78f5b04bc82bf7a15a and template : shared-template1 not found"{}
│ 

# Results of terraform apply -destroy   (2nd try)

  Enter a value: yes

module.mso.mso_schema_site.site1: Destroying... [id=614ffb40562ca8085d6bacc8]
module.mso.mso_schema_site.site1: Destruction complete after 0s
module.mso.mso_schema.schema1: Destroying... [id=6181ceeb210000546b48e6f9]
module.mso.mso_schema.schema1: Destruction complete after 0s
module.mso.mso_tenant.tenant: Destroying... [id=6181ceea210000566b48e6f8]
module.mso.mso_tenant.tenant: Destruction complete after 1s

Apply complete! Resources: 0 added, 0 changed, 3 destroyed.

# attaching entire resources.tf file
[resources.tf.txt](https://github.com/CiscoDevNet/terraform-provider-mso/files/7464690/resources.tf.txt)
:

**Comment by lhercot** [comment]
Closing as this was due to a wrong order of operations because of missing dependencies.
