### ISSUE TITLE
mso_schema_template_contract wrong deprecation

### ISSUE THREAD

**Issue by apellini** [CiscoDevNet/terraform-provider-mso#78]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v1.0.10
on linux_amd64
+ provider registry.terraform.io/ciscodevnet/mso v0.3.2

### MSO version

* Version: 2.2(3j)

### APIC version and APIC Platform for Site Level Resources

* V 4.2(3l) and on-prem.

### Affected Resource(s)

* mso_schema_template_contract

### Terraform Configuration Files

Working with deprecation waring code:

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
resource "mso_schema_template_contract" "MSO_SCHEMA_TEMPLATE_CONTRACT" {
  for_each = {
  for contract in local.contracts :
    format("%s|%s|%s", "${contract.filter_relationship.filter_name}", "${contract.contract_name}", "${contract.schema}") => contract
  }
  schema_id = each.value.schema_id
  template_name = each.value.template_name
  contract_name = each.value.contract_name
  display_name = each.value.display_name
  filter_relationships = {
    filter_schema_id = each.value.filter_relationship.filter_schema_id
    filter_template_name = each.value.filter_relationship.filter_template_name
    filter_name = each.value.filter_relationship.filter_name
  }
  directives = each.value.directives
}
```
Failed code:

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
resource "mso_schema_template_contract" "MSO_SCHEMA_TEMPLATE_CONTRACT" {
  for_each = {
  for contract in local.contracts :
    format("%s|%s|%s", "${contract.filter_relationship.filter_name}", "${contract.contract_name}", "${contract.schema}") => contract
  }
  schema_id = each.value.schema_id
  template_name = each.value.template_name
  contract_name = each.value.contract_name
  display_name = each.value.display_name
  filter_relationship = {
    filter_schema_id = each.value.filter_relationship.filter_schema_id
    filter_template_name = each.value.filter_relationship.filter_template_name
    filter_name = each.value.filter_relationship.filter_name
  }
  directives = each.value.directives
}
```

### Expected Behavior
Launching terraform plan/apply with filter_relationship on this resource has to be accepted and applyed without any warnings, instead for filter_relationships will be applyed with deprecation warnings.

### Actual Behavior
if we launch terraform with this resource model with filter_relationship terraform goes in error and suggest to user filter_relationships instead:

```
â•·
â”‚ Error: Unsupported argument
â”‚ 
â”‚   on modules/contracts/main.tf line 94, in resource "mso_schema_template_contract" "MSO_SCHEMA_TEMPLATE_CONTRACT":
â”‚   94:   filter_relationship = {
â”‚ 
â”‚ An argument named "filter_relationship" is not expected here. Did you mean "filter_relationships"?
â•µ
```

Instead if we use filter_relationships:

```
â•·
â”‚ Warning: "filter_relationships": [DEPRECATED] use filter_relationship instead
â”‚ 
â”‚   with module.contracts.mso_schema_template_contract.MSO_SCHEMA_TEMPLATE_CONTRACT,
â”‚   on modules/contracts/main.tf line 85, in resource "mso_schema_template_contract" "MSO_SCHEMA_TEMPLATE_CONTRACT":
â”‚   85: resource "mso_schema_template_contract" "MSO_SCHEMA_TEMPLATE_CONTRACT" {
â”‚ 
â”‚ (and 4 more similar warnings elsewhere)
â•µ
```

### Steps to Reproduce

1. Create a main.tf file using this resource model and use filter_relationship.
2. Run `terraform apply`

* #0000

**Comment by lhercot** [comment]
filter_relationship is a block and not a map as before so you need to remove that = and use multiple blocks if you have multiple filters.

See https://github.com/CiscoDevNet/terraform-provider-mso/blob/master/examples/schema_template_contract/main.tf for example.

**Comment by apellini** [comment]
ok thanks has worked but if you see in documentation is written as map:

filter_relationship - (Required if filter_relationships is not used) Map to provide Filter Relationships.

Also the example displays filter_relationships that is deprecated, so it is better to display right documentation.

**Comment by lhercot** [comment]
We will fix the doc and doc example. Thanks for reporting the issue.
