### ISSUE TITLE
mso_tenant crashes terraform after creating on-prem apic site association

### ISSUE THREAD

**Issue by IbrBsIs** [CiscoDevNet/terraform-provider-mso#8]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

* Terraform v0.14.4
* The same issues when using ver 13

### MSO version

* V 3.1.1g
* The same behavior with versions 2.x

### APIC version and APIC Platform for Site Level Resources

* V 4.2.(3n), 4.2(4o) on-prem.

### Affected Resource(s)

* mso_tenant
* mso_site

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp

data "mso_site" "LAB" {                                                                                                              
  name = "LAS LAB"                                                                                                                       
} 

data "mso_user" "admin" {                                                                                                                
    username = "admin"                                                                                                                   
} 

resource "mso_tenant" "NS" {
  name         = "NS1"
  display_name = "NS1"
  description  = "NS1"
  site_associations { 
    site_id = data.mso_site.LAB.id 
  }
  user_associations {
    user_id = data.mso_user.admin.id
  }
}

```

### Panic Output

https://gist.github.com/IbrBsIs/8f9cb7e54aa12e27c90a1f70e1ddfa4d

### Expected Behavior

* tenant created, associated with site(s) and tf proceeds with the rest of configuration

### Actual Behavior

* tenant created, associated with site, plugin exits with error, terraform crashes, resource not populated to state

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by nkatarmal-crest** [comment]
This issue has been fixed in the latest version of the provider, please verify the same with the latest version.

**Comment by IbrBsIs** [comment]
It works now. Thanks!
