### ISSUE TITLE
Support for Service EPGs

### ISSUE THREAD

**Issue by robvand** [CiscoDevNet/terraform-provider-mso#9]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The MSO provider does not support EPGs of the Service type yet. 

### New or Affected Resource(s) + MSO Class(es):

* mso_schema_site_anp_epg

### MSO version

* V 3.1.1g

### APIC version and APIC Platform for Site level Resources

* V Cloud APIC Azure 5.1(2)

### Potential Terraform Configuration

```hcl
resource "mso_schema_site_anp_epg" "site_anp_epg" {
  schema_id = "5c4d9fca270000a101f8094a"
  template_name = "Template1"
  site_id = "5c7c95d9510000cf01c1ee3d"
  anp_name = "ANP"
  epg_name = "DB"
  epg_type = "Service / Application"
  deployment_type =  " Cloud Native / Cloud Native Managed / Third Party"
  access_type = "Private / Public / Public-Private"
  service_type = "Azure service XYZ"
  selector = "Selector1"
}
```

### References

* #0000

**Comment by anvitha-jain** [comment]
Requires support for Private Link label (type list) at site level
