### ISSUE TITLE
Unable to add site to NDO on ND using mso_site

### ISSUE THREAD

**Issue by aj-cruz** [CiscoDevNet/terraform-provider-mso#92]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.1.0
on linux_amd64
+ provider registry.terraform.io/ciscodevnet/mso v0.4.1

### MSO version

NDO 3.5.2f on ND 2.1(1e)

### APIC version and APIC Platform for Site Level Resources

5.2(1g) on-prem

### Affected Resource(s)

mso_site

### Terraform Configuration Files

```hcl
resource "mso_rest" "NDSites" {
    count = length(var.sites)
    path = "api/config/v2/addsite/"
    method = "POST"
    payload = <<EOF
{
    "name": "${var.sites[count.index].name}",
    "url": "${var.sites[count.index].apic_ip}",
    "siteType": "ACI",
    "aci": {
        "userName": "${var.sites[count.index].apic_username}",
        "password": "${var.sites[count.index].apic_password}",
        "inbandEpgDN": "",
        "loginDomain": ""
    },
    "latitude": "",
    "longitude": "",
    "securityDomains": []
}
EOF
}

resource "mso_site" "site" {
  depends_on = [
    mso_rest.NDSites
  ]
  count = length(var.sites)
  name         = var.sites[count.index].name
  username     = var.sites[count.index].apic_username
  password     = var.sites[count.index].apic_password
  apic_site_id = var.sites[count.index].site_id
  urls         = ["https://${var.sites[count.index].apic_ip}"]
}
```

I also tried creating the site in NDO using mso_rest but got the same results:
```hcl
resource "mso_rest" "NDOSites" {
    count = length(var.sites)
    path = "api/v2/sites/manage"
    method = "POST"
    payload = <<EOF
{
    "id": "",
    "common": {
        "name": "${var.sites[count.index].name}",
        "displayName": "${var.sites[count.index].name}",
        "urls": [
            "https://${var.sites[count.index].apic_ip}:443"
        ],
        "platformType": "Apic",
        "siteVersion": "",
        "siteId": "${var.sites[count.index].site_id}"
    }
}
EOF
}
```
### Debug Output

[Trace](https://gist.github.com/aj-cruz/8ef867ac8354e3bf840ee3b88d8d981e)

### Expected Behavior

Site changed to managed in NDO and assigned site ID

### Actual Behavior

The Terraform apply runs without error and adds the object to state, but nothing is reflected in the GUI, the site still shows "Unmanaged"

### Steps to Reproduce

1. `terraform apply`

### References

#72

**Comment by lhercot** [comment]
@aj-cruz I am able to manipule a site in NDO with the following:
```
resource "mso_site" "ndo_site_1" {
  name             = "test_nd"
  apic_site_id     = "18"
}
```

Are you using platform="nd" in your provider section to tell the provider you are using a NDO?

**Comment by aj-cruz** [comment]
@lhercot Nope I missed the addition of that parameter to the provider, sorry. That's it.
