### ISSUE TITLE
mso_schema_template_filter_entry error on destroy

### ISSUE THREAD

**Issue by apellini** [CiscoDevNet/terraform-provider-mso#93]
### Terraform Version
Terraform v1.0.10
on linux_amd64

CiscoDevNet/mso 0.4.0

### MSO version

* V 2.2(3j)

### APIC version and APIC Platform for Site Level Resources

* V 4.2(3I) and on-prem

### Affected Resource(s)

* mso_schema_template_filter_entry
### Terraform Configuration Files

```hcl
resource "mso_schema_template_filter_entry" "MSO_SCHEMA_TEMPLATE_FILTER_ENTRY" {
  for_each = {
  for filter in local.filters :
    format("%s|%s|%s", "${filter.entry_name}", "${filter.name}", "${filter.schema}") => filter
  }
  schema_id = each.value.schema_id
  template_name = each.value.template_name
  name = each.value.name
  display_name = each.value.display_name
  entry_name = each.value.entry_name
  entry_display_name = each.value.entry_display_name
  destination_from = each.value.destination_from
  destination_to = each.value.destination_to
  ether_type = each.value.ether_type
  ip_protocol = each.value.ip_protocol

  lifecycle {
    create_before_destroy = true
  }
}
```

We have modified our YAML from:

```yaml
Filter1:
  tcp_443:
    start: 443
    end: 443
    protocol: tcp
    ether: ip
  tcp_80:
    start: 80
    end: 80
    protocol: tcp
    ether: ip
```

To:

```yaml
Filter1:
  tcp_https:
    start: https
    end: https
    protocol: tcp
    ether: ip
  tcp_http:
    start: http
    end: http
    protocol: tcp
    ether: ip
```

### Debug Output
`
module.contracts.mso_schema_template_filter_entry.MSO_SCHEMA_TEMPLATE_FILTER_ENTRY["tcp_443|Filter1|Schema1"]: Destroying... [id=tcp_443]
module.contracts.mso_schema_template_filter_entry.MSO_SCHEMA_TEMPLATE_FILTER_ENTRY["tcp_443|Filter1|Schema1"]: Destruction complete after 0s
module.contracts.mso_schema_template_filter_entry.MSO_SCHEMA_TEMPLATE_FILTER_ENTRY["tcp_80|Filter1|Schema2"]: Destroying... [id=tcp_80]
module.contracts.mso_schema_template_filter_entry.MSO_SCHEMA_TEMPLATE_FILTER_ENTRY["tcp_80|Filter1|Schema2"]: Destruction complete after 0s
module.contracts.mso_schema_template_filter_entry.MSO_SCHEMA_TEMPLATE_FILTER_ENTRY["tcp_443|Filter1|Schema2"]: Destroying... [id=tcp_443]
module.contracts.mso_schema_template_filter_entry.MSO_SCHEMA_TEMPLATE_FILTER_ENTRY["tcp_80|Filter1|Schema1"]: Destroying... [id=tcp_80]
module.contracts.mso_schema_template_filter_entry.MSO_SCHEMA_TEMPLATE_FILTER_ENTRY["tcp_http|Filter1|Schema1"]: Creating...
module.contracts.mso_schema_template_filter_entry.MSO_SCHEMA_TEMPLATE_FILTER_ENTRY["tcp_http|Filter1|Schema1"]: Creation complete after 0s [id=tcp_http]
module.contracts.mso_schema_template_filter_entry.MSO_SCHEMA_TEMPLATE_FILTER_ENTRY["tcp_https|Filter1|Schema2"]: Creating...
module.contracts.mso_schema_template_filter_entry.MSO_SCHEMA_TEMPLATE_FILTER_ENTRY["tcp_https|Filter1|Schema2"]: Creation complete after 0s [id=tcp_https]
module.contracts.mso_schema_template_filter_entry.MSO_SCHEMA_TEMPLATE_FILTER_ENTRY["tcp_http|Filter1|Schema2"]: Creating...
module.contracts.mso_schema_template_filter_entry.MSO_SCHEMA_TEMPLATE_FILTER_ENTRY["tcp_http|Filter1|Schema2"]: Creation complete after 1s [id=tcp_http]
module.contracts.mso_schema_template_filter_entry.MSO_SCHEMA_TEMPLATE_FILTER_ENTRY["tcp_https|Filter1|Schema1"]: Creating...
module.contracts.mso_schema_template_filter_entry.MSO_SCHEMA_TEMPLATE_FILTER_ENTRY["tcp_https|Filter1|Schema1"]: Creation complete after 0s [id=tcp_https]
╷
│ Error: "Invalid Reference: Unable to find filter 'FilterRef(61824b3412000082872f56a4,Template1,Filter1)'"{}
│ 
│ 
╵
╷
│ Error: "Invalid Reference: Unable to find filter 'FilterRef(61824c02130000809af0723f,Template2,Filter1)'"{}
│ 
│ 
`

### Expected Behavior
Terraform has to create before new filter entries and after try to destroy the oldest ones.

Also if you try a new terraform apply the operation finishes without errors.

### Actual Behavior
As displayed in the log terraform has destroyed before create and giving in back in error.

### Steps to Reproduce
Try to modify a filter with a single entry

1. `terraform apply`

* #0000

**Comment by shrsr** [comment]
@apellini 
Can you please try running terraform with the following command:
terraform apply -parallelism=1

**Comment by shrsr** [comment]
@apellini Did `terraform apply -parallelism=1` work for you?

**Comment by shrsr** [comment]
Closing the issue. Please let us know if you have any questions regarding terraform apply -parallelism=1
command.
