### ISSUE TITLE
Crash while importing site

### ISSUE THREAD

**Issue by justlikeef** [CiscoDevNet/terraform-provider-mso#94]
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ImportResourceState call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-mso_v0.4.1.exe plugin:

panic: interface conversion: interface {} is nil, not []interface {}

goroutine 67 [running]:
github.com/terraform-providers/terraform-provider-mso/mso.resourceMSOSiteImport(0xc000210000, 0x10ef6e0, 0xc0001cc930, 0x8, 0xc0003bcb68, 0x1d90e01, 0x0, 0x2)
        github.com/terraform-providers/terraform-provider-mso/mso/resource_mso_site.go:149 +0xfcd
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).ImportState(0xc000064080, 0xc000153ad0, 0xc0002da060, 0x18, 0x7bbb2b, 0xc00002c2a0, 0x24, 0x24, 0x10d84a0)
        github.com/hashicorp/terraform-plugin-sdk@v1.14.0/helper/schema/provider.go:390 +0x292
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ImportResourceState(0xc000006028, 0x13c1ac0, 0xc000656150, 0xc000380180, 0xc000006028, 0xc000656150, 0xc0001f9b78)
        github.com/hashicorp/terraform-plugin-sdk@v1.14.0/internal/helper/plugin/grpc_provider.go:953 +0xf3
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ImportResourceState_Handler(0x1107580, 0xc000006028, 0x13c1ac0, 0xc000656150, 0xc0002e2060, 0x0, 0x13c1ac0, 0xc000656150, 0xc00002c2a0, 0x24)
        github.com/hashicorp/terraform-plugin-sdk@v1.14.0/internal/tfplugin5/tfplugin5.pb.go:3323 +0x21e
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000084f00, 0x13cd1a0, 0xc000085e00, 0xc000066100, 0xc000127380, 0x1b354f8, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.27.1/server.go:1024 +0x508
google.golang.org/grpc.(*Server).handleStream(0xc000084f00, 0x13cd1a0, 0xc000085e00, 0xc000066100, 0x0)
        google.golang.org/grpc@v1.27.1/server.go:1313 +0xd44
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000094000, 0xc000084f00, 0x13cd1a0, 0xc000085e00, 0xc000066100)
        google.golang.org/grpc@v1.27.1/server.go:722 +0xa8
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.27.1/server.go:720 +0xa8

Error: The terraform-provider-mso_v0.4.1.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v1.1.2
on windows_amd64
+ provider registry.terraform.io/ciscodevnet/mso v0.4.1

### MSO version

* V 0.4.1

### APIC version and APIC Platform for Site Level Resources

* V x.x.x and on-prem/cloud-aws/cloud-azure/all.

### Affected Resource(s)

* mso_site

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform import mso_site.st-[sitename]`

### References

* #0000

**Comment by shrsr** [comment]
@justlikeef 
1. Can you give us the version of MSO/NDO you are trying to import the site from?
2. Can you also use `export TF_LOG=“TRACE”`before you run the import command and share the log with us?
