### ISSUE TITLE
Error importing user

### ISSUE THREAD

**Issue by justlikeef** [CiscoDevNet/terraform-provider-mso#95]
Error attempting to import users

╷
│ Error: The mso_user resources is not supported on ND-based MSO/NDO. Use ND provider for manipulating users on ND-based MSO/NDO.
│
│
╵

These users don't exist in ND directly because they are Radius, not local users.  They should be able to be imported as unmanaged if they are not local users.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### MSO version

* V 3.4(1a)

### APIC version and APIC Platform for Site Level Resources

* V x.x.x and on-prem/cloud-aws/cloud-azure/all.

### Affected Resource(s)

* mso_user

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by shrsr** [comment]
@justlikeef 
What is the use case for this? 
Remote users need to first login into ND to be able to be used to associate with a tenant. If you want to lookup information about users please use the data source.

**Comment by justlikeef** [comment]
Users are not local, they log in through TACACs/LDAP/Radius, etc. so they
don't appear in the ND user database, but their user ID is associated with
a NDO object.

When you click on their ID in NDO, you can see what domain they came from.
That's the information I need to be able to query and add so that the user
has access to the NDO object.


Thanks,
Rob

**Comment by shrsr** [comment]
Can you refer to https://registry.terraform.io/providers/CiscoDevNet/mso/latest/docs/data-sources/user
Let me know if this helps.

**Comment by shrsr** [comment]
@justlikeef Did the data source for mso_user work for you?

**Comment by shrsr** [comment]
Closing the issue. Please open a new issue if it persists or you have any questions regarding data source.
