### ISSUE TITLE
static association with vPC

### ISSUE THREAD

**Issue by cgonzalezgar** [CiscoDevNet/terraform-provider-mso#97]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.1.4
on windows_amd64

provider registry.terraform.io/ciscodevnet/mso v0.4.1

### MSO version

ND: Version 2.1(1d)
NDO: Version: 3.5(2f)

### APIC version and APIC Platform for Site Level Resources

Version: 5.2(2f)

### Affected Resource(s)

mso_schema_site_anp_epg_static_port 

### Terraform Configuration Files

```hcl
resource "mso_schema_site_anp_epg_static_port" "static_port" {
	
	schema_id 			= "61b9d0c6200000bfd769c578"
	template_name 		= "LAB_CZA_Tpl"
	site_id 			= "61b30db1a630e35f873cadc0"
	anp_name 			= "LAB_APP"
	epg_name 			= "Test_EPG"
	path_type			= "vpc"
	deployment_immediacy = "lazy"
	path 				= "CZAWS01-02_Po500_VPCIntPol"
	vlan 				= 200
	mode 				= "native"
```

### Actual Behavior

In the resource definition, leaf and path are mandatory fields

* leaf - (Required) The leaf of the static port.
* path - (Required) The path of the static port.

but they are single values. And in a vPC there are two leaf switches, and, at least, 2 ports.

Using the GUI, the dialog box for static port binding changes if the path type is vPC, to only require the path (just the vPC name, not the nodes and ports involved) and the vlan encap.
I guess the required fileds in the resource should vary based on the path_type attribute.

How can I implement a EPG to vPC association?

Regards,
Carlos

**Comment by shrsr** [comment]
@cgonzalezgar When we have **path_type="vpc"**, we concatenate the leaf as shown in the example below. Does this answer the question?



```
resource "mso_schema_site_anp_epg_static_port" "static_port" {
	schema_id                       = "61b9d0c6200000bfd769c578"
	template_name               = "LAB_CZA_Tpl"
	site_id                              = "61b30db1a630e35f873cadc0"
	anp_name 			= "LAB_APP"
	epg_name 			= "Test_EPG"
        leaf                                    = "101-102"
	path_type			= "vpc"
	deployment_immediacy = "lazy"
	path 				= "CZAWS01-02_Po500_VPCIntPol"
	vlan 				= 200
	mode 				= "native"
}
```

**Comment by cgonzalezgar** [comment]
Hi Shreyas

Yes, I've been able to associate the vPC concatenating the leaf.
Thanks four your help !!
